### ISSUE TITLE
Persist login with a cookie

### ISSUE THREAD

**Issue by jolyonruss** [asylum-connect/asylumconnect-catalog#11]
As an Asylee 
I want to log into the website and be able to refresh the page and still be logged in
So that I don't have to log in every time I visit the catalog

-----

We have the login logic stubbed out but need to store the JWT in a cookie to allow sessions to persist longer than one page. I've had good experiences with using [js-cookie](https://github.com/js-cookie/js-cookie)

**Comment by jolyonruss** [comment]
Hi @DanielKim1 - I replied to you in Slack but just reiterating here, go for it!

**Comment by jillh510** [comment]
@DanielKim1 the PR is marked 'WIP' - anything you need to help resolve remaining questions? Thanks!
