### ISSUE TITLE
Update Header component to match original site

### ISSUE THREAD

**Issue by jolyonruss** [asylum-connect/asylumconnect-catalog#12]
We have a stub of the Header component, but this needs to match the previous version of the website.

Also, now that we have a `_document.js` it can be implemented as a sibling of 
```
<Main />
<NextScript />
```

It should use Materia-UI components as much as possible and include Google translate selection dropdown thing.

#### Important
This should not include the Privacy and Disclaimer Dialogs, that's covered in this https://github.com/Ragtagteam/asylumconnect-catalog/issues/14 issue

**Comment by tek08** [comment]
Quick note on Google Translate:  

https://translate.google.com/intl/en/about/website/

> We no longer provide new access to Google Translate's Website Translator. This change does not affect existing use of the Website Translator.

> We encourage users looking to translate webpages to use browsers that support translation natively.

**Comment by tek08** [comment]
#43

**Comment by tek08** [comment]
Have created #43.
