### ISSUE TITLE
Create Footer component

### ISSUE THREAD

**Issue by jolyonruss** [asylum-connect/asylumconnect-catalog#13]
We need a Footer component, this can be implemented in `_document.js` in the same way as the Header.

It should use Materia-UI components as much as possible

**Comment by jolyonruss** [comment]
Thanks @phpsmith for taking this on. I wasn't very clear in the issue description - sorry.

The Footer needs to replicate the Footer of the existing site https://catalog.asylumconnect.org/

**Comment by phpsmith** [comment]
@jolyonruss No worries, I'll get this updated.

**Comment by phpsmith** [comment]
#35 PR added this task.

**Comment by phpsmith** [comment]
Whoops - closed wrong issue.
