### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by dryan** [asylum-connect/asylumconnect-catalog#21]
* [ ] copy https://github.com/RagtagOpen/project-skeleton/blob/master/CONTRIBUTING.md to this project
* [ ] find and replace "Project Name" with "Asylum Connect Catalog"

**Comment by eroncanc** [comment]
being done with #27 ?

**Comment by jolyonruss** [comment]
Yes @eroncanc it looks like @vaknin has picked this up.

@dryan can you add @vaknin as a contributor?

**Comment by jolyonruss** [comment]
Closing this since I merged #27
