### ISSUE TITLE
Add a CONTRIBUTORS file

### ISSUE THREAD

**Issue by dryan** [asylum-connect/asylumconnect-catalog#22]
Following the format of https://github.com/RagtagOpen/project-skeleton/blob/master/CONTRIBUTORS, add a `CONTRIBUTORS` file with each person who has contributed code or filed an issue.

Don't forget to add yourself!

**Comment by tpiekarski** [comment]
I'll be glad to provide a PR for this little task and collect all contributors of code and issues :)
