### ISSUE TITLE
Setup /public directory for serving static files

### ISSUE THREAD

**Issue by jolyonruss** [asylum-connect/asylumconnect-catalog#29]
**Is your feature request related to a problem? Please describe.**
We don't have anywhere to load static files from

**Describe the solution you'd like**
A `/public` directory at the top level of the project where files can be served from

**Describe alternatives you've considered**
n/a

**Additional context**
Here's a link to some documentation around serving static files - https://expressjs.com/en/starter/static-files.html

**Comment by phpsmith** [comment]
#35 PR added this task. Closing.
