### ISSUE TITLE
Setup E2E testing

### ISSUE THREAD

**Issue by jolyonruss** [asylum-connect/asylumconnect-catalog#8]
As an Eng
I want to setup E2E testing
So that I can have confidence in releasing code that will work as expected

**Comment by dryan** [comment]
Once this is done, I want to require CI passing before a PR can be merged. That can be done at https://github.com/asylum-connect/asylumconnect-catalog/settings/branch_protection_rules/5640293, though I'm not sure what permissions level is needed to make the change.

**Comment by jolyonruss** [comment]
@dryan sounds good - we have this at work. I can't view the branch protection rules page, but we'll work that out once we have CI integrated

**Comment by jillh510** [comment]
@AaronSofaer adding this one to your list because it had "CI" in it
